'use client';
import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

const translations = {
  fr: {
    home: "Accueil",
    profile: "Profil",
    notifications: "Notifications",
    messages: "Messages",
    following: "Comptes suivis",
    follow: "Suivre",
    unfollow: "Ne plus suivre",
    editProfile: "Modifier le profil",
    publish: "Publier",
    placeholder: "Comment ça va ?",
    noPost: "Aucun post pour l'instant.",
    noMessage: "Aucun message pour l'instant.",
    noNotif: "Aucune notification pour l'instant.",
    notifDesc: "Les mentions et interactions apparaîtront ici",
    msgDesc: "Tes conversations privées apparaîtront ici",
    save: "Enregistrer",
    loading: "Chargement...",
    subscriptions: "abonnements",
    followers: "abonnés",
    bornOn: "Né(e) le",
    name: "Nom",
    bio: "Bio",
    birthdate: "Date de naissance",
    changePic: "Clique pour changer la photo",
    bioPlaceholder: "Parle de toi en quelques mots",
    settings: "Paramètres",
    account: "Compte",
    logout: "Déconnexion",
    appearance: "Apparence",
    theme: "Thème",
    language: "Langue",
    themeDark: "Sombre",
    themeLight: "Clair",
    legal: "Informations légales",
    terms: "Conditions d'utilisation",
    privacy: "Politique de confidentialité",
    cookies: "Politique relative aux cookies",
    accessibility: "Accessibilité",
    ads: "Informations sur les publicités",
    moreAbout: "Plus / À propos",
    userNotFound: "Utilisateur introuvable.",
    postNotFound: "Post introuvable.",
    back: "Retour",
    yourReply: "Votre réponse :",
    writeHere: "écrire ici",
    noComment: "Aucun commentaire pour l'instant.",
    commentsLabel: "commentaires",
    likesLabel: "likes",
    followingEmpty: "Tu ne suis personne pour l'instant.",
    publishError: "Erreur lors de la publication.",
    accountRestricted: "Action impossible : votre compte est actuellement restreint.",
    profilePicError: "Erreur lors de la mise à jour de la photo.",
    profileUpdateError: "Erreur lors de la mise à jour du profil.",
    admin: "Administration",
    createAccount: "Créer un compte",
    email: "Courriel",
    username: "Nom d'utilisateur",
    password: "Mot de passe",
    createAccountBtn: "Créer le compte",
    usersList: "Utilisateurs",
    roleChangeNote: "Un changement de rôle prend effet à la prochaine connexion de l'utilisateur concerné.",
    loadUsersError: "Erreur lors du chargement des utilisateurs.",
    statusChangeError: "Erreur lors du changement de statut.",
    roleChangeError: "Erreur lors du changement de rôle.",
    createAccountError: "Erreur lors de la création du compte.",
    accountCreatedOk: "Compte créé avec succès.",
    statusActive: "actif",
    statusSuspended: "suspendu",
    statusBanned: "banni",
    roleUser: "utilisateur",
    roleModerator: "modérateur",
    roleAdmin: "admin",
  },
  en: {
    home: "Home",
    profile: "Profile",
    notifications: "Notifications",
    messages: "Messages",
    following: "Following",
    follow: "Follow",
    unfollow: "Unfollow",
    editProfile: "Edit profile",
    publish: "Post",
    placeholder: "What's on your mind?",
    noPost: "No posts yet.",
    noMessage: "No messages yet.",
    noNotif: "No notifications yet.",
    notifDesc: "Mentions and interactions will appear here",
    msgDesc: "Your private conversations will appear here",
    save: "Save",
    loading: "Loading...",
    subscriptions: "following",
    followers: "followers",
    bornOn: "Born on",
    name: "Name",
    bio: "Bio",
    birthdate: "Date of birth",
    changePic: "Click to change photo",
    bioPlaceholder: "Tell us a bit about yourself",
    settings: "Settings",
    account: "Account",
    logout: "Log out",
    appearance: "Appearance",
    theme: "Theme",
    language: "Language",
    themeDark: "Dark",
    themeLight: "Light",
    legal: "Legal information",
    terms: "Terms of use",
    privacy: "Privacy policy",
    cookies: "Cookies policy",
    accessibility: "Accessibility",
    ads: "Advertising information",
    moreAbout: "More / About",
    userNotFound: "User not found.",
    postNotFound: "Post not found.",
    back: "Back",
    yourReply: "Your reply:",
    writeHere: "type here",
    noComment: "No comments yet.",
    commentsLabel: "comments",
    likesLabel: "likes",
    followingEmpty: "You're not following anyone yet.",
    publishError: "Failed to publish.",
    accountRestricted: "Action not allowed: your account is currently restricted.",
    profilePicError: "Failed to update photo.",
    profileUpdateError: "Failed to update profile.",
    admin: "Administration",
    createAccount: "Create an account",
    email: "Email",
    username: "Username",
    password: "Password",
    createAccountBtn: "Create account",
    usersList: "Users",
    roleChangeNote: "A role change takes effect the next time the affected user logs in.",
    loadUsersError: "Failed to load users.",
    statusChangeError: "Failed to change status.",
    roleChangeError: "Failed to change role.",
    createAccountError: "Failed to create account.",
    accountCreatedOk: "Account created successfully.",
    statusActive: "active",
    statusSuspended: "suspended",
    statusBanned: "banned",
    roleUser: "user",
    roleModerator: "moderator",
    roleAdmin: "administrator",
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('fr');

  function toggleLang() {
    setLang(l => l === 'fr' ? 'en' : 'fr');
  }

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
